name: Deploy Lambda Function

on:
  push:
    paths:
      - "src/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for Lambda function
        run: cd src && zip -r code.zip .

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:eu-central-1:637423656827:function:TestCICDFunction --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
