name: Deploy Lambda Function

on:
  push:
    paths:
      - "src/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zip tool
        run: sudo apt-get install zip -y

      - name: Create Zip file for Lambda function
        run: cd src && zip -r code.zip .

      - name: Install AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:eu-central-1:637423656827:function:TestCICDFunction --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
